# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum of a numeric vector
#'
#' A toolchain smoke test, not a statistical routine. It exists to prove that
#' the C++ compiler, the Rcpp/RcppArmadillo headers, and the R binding all
#' work end to end on this machine. Delete it once a real numeric core lands.
#'
#' @param x A numeric vector.
#'
#' @return A length-one numeric vector: the sum of `x`. The sum of an empty
#'   vector is `0`.
#'
#' @examples
#' vec_sum(c(1, 2, 3))
#'
#' @export
vec_sum <- function(x) {
    .Call(`_bllnn_vec_sum`, x)
}

